### ISSUE TITLE
Could not start watchman; falling back to NodeWatcher for file system events.

### ISSUE THREAD

**Issue by hongbo-miao** [learnapollo/pokedex-angular#1]
Tried to run by `yarn start`, got this error:

```bash
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ENOENT: no such file or directory, stat '/pokedex-angular/playground/src/assets'
Error: ENOENT: no such file or directory, stat '/pokedex-angular/playground/src/assets'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at /pokedex-angular/playground/node_modules/angular-cli/plugins/glob-copy-webpack-plugin.js:16:64
    at Array.map (native)
    at GlobCopyWebpackPlugin.apply (/pokedex-angular/playground/node_modules/angular-cli/plugins/glob-copy-webpack-plugin.js:16:29)
    at Compiler.apply (/pokedex-angular/playground/node_modules/tapable/lib/Tapable.js:233:16)
    at WebpackOptionsApply.process (/pokedex-angular/playground/node_modules/webpack/lib/WebpackOptionsApply.js:59:18)
    at webpack (/pokedex-angular/playground/node_modules/webpack/lib/webpack.js:28:48)
    at Class.exports.default.Task.extend.run (/pokedex-angular/playground/node_modules/angular-cli/tasks/serve-webpack.js:25:27)
    at /pokedex-angular/playground/node_modules/angular-cli/commands/serve.js:92:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by marktani** [comment]
can you try to create a new folder `assets` at the required location?
I think the folder is empty and therefore not handled by git.

If this fixes it, I can put an empty `.gitignore` there.

**Comment by hongbo-miao** [comment]
Hi @marktani you are right. Actually the assets folder does exist. It is just at a wrong place.

**Comment by marktani** [comment]
Thanks! Hope you like the playground :slightly_smiling_face:

**Comment by daliri72** [comment]
Your answer is [here ](https://github.com/angular/angular-cli/issues/1390#issuecomment-383370560)
